# Generated by Django 3.1.3 on 2020-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
